### PR TITLE
fix 0.0f assign

### LINKED ISSUE #197: c2v err logic Bug
c2v generates the wrong v code, which produces a different output. 
the main.c file content: 
```c
#include <stdio.h>

// Function for CPU-intensive computation
void cpu_intensive_task(int iteration) {
    long iterations = 1000000000; // Number of iterations to control computation intensity
    double pi = 0.0f;

    printf("Iteration %d started\n", iteration);

    // Calculate pi using the Leibniz formula
    for (long i = 0; i < iterations; i++) {
        double sign = (i % 2 == 0 ? 1.0 : -1.0); // Alternate between 1 and -1
        pi += sign / (2.0 * i + 1);
    }
    pi *= 4.0; // Obtain the approximate value of pi

    printf("Iteration %d finished, calculated pi = %.10f\n", iteration, pi);
}

int main() {
    int num_iterations = 1; // Default to 1 iterations, adjustable

    // Execute the task multiple times
    for (int i = 0; i < num_iterations; i++) {
        cpu_intensive_task(i);
    }

    printf("All iterations completed.\n");
    return 0;
}
```

and the converted v main.v file:
```v
@[translated]
module main

// Function for CPU-intensive computation
fn cpu_intensive_task(iteration int) {
	iterations := 1000000000
	// Number of iterations to control computation intensity
	pi := 0
	C.printf(c'Iteration %d started\n', iteration)
	// Calculate pi using the Leibniz formula
	for i := 0; i < iterations; i++ {
		sign := (if i % 2 == 0 { 1 } else { -1 })
		// Alternate between 1 and -1
		pi += sign / (2 * i + 1)
	}
	pi *= 4
	// Obtain the approximate value of pi
	C.printf(c'Iteration %d finished, calculated pi = %.10f\n', iteration, pi)
}

fn main() {
	num_iterations := 1
	// Default to 1 iterations, adjustable
	// Execute the task multiple times
	for i := 0; i < num_iterations; i++ {
		cpu_intensive_task(i)
	}
	C.printf(c'All iterations completed.\n')
	return
}
```

when compiled with clang on mac `clang -o main main.c && ./main`, the result of main.c is: 
```
Iteration 0 started
Iteration 0 finished, calculated pi = 3.1415926526
All iterations completed.
```

while translating and running with v `v translate main.c` then `v run main.v`, the result of main.v is:
```
Iteration 0 started
Iteration 0 finished, calculated pi = 0.0000000000
All iterations completed.
```

### PR DESCRIPTION
**Pull request by felipensp**
Fix #197

### CODE REVIEW

**Review by Serendipithub — CHANGES_REQUESTED** [review]

File: tests/26.assign_zerof.c [hunk 1]
```diff
@@ -0,0 +1,3 @@
+int main() {
+    double a = 0.0f;
```
[the remark this answers is not in the document]
Comment (felipensp) [reply tests/26.assign_zerof.c:2]: Thanks.

File: tests/26.assign_zerof.c [hunk 2]
```diff
@@ -0,0 +1,4 @@
...
+    double b = 0;
+}
```
Comment (Delta456) [inline tests/26.assign_zerof.c:4]: add newline here

Comment (felipensp) [reply tests/26.assign_zerof.c]: Ok thanks.
